### ISSUE TITLE
Updating from 3.5.2 => 3.5.3 triggers error with FileEngine.php(384): mkdir()

### ISSUE THREAD

**Issue by makallio85** [cakephp/cakephp#11251]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.3
* Platform and Target: Windows 7, PHP 7.0.0

### What you did
Updated from 3.5.2 to 3.5.3

### What happened
Following error was triggered

```
2017-09-28 15:30:24 Error: [ErrorException] mkdir() [<a href='https://secure.php.net/function.mkdir'>function.mkdir</a>]: File exists in C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Cache\Engine\FileEngine.php:384.
Request URL: /rental-agreements/add/2
Referer URL: http://localhost/vuokravalvonta/rental-properties/view/2
Stack Trace:
#0 [internal function]: App\Error\AppErrorHandler->handleError(2, 'mkdir() [<a hre...', 'C:\\xampp\\htdocs...', 384, Array)
#1 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Cache\Engine\FileEngine.php(384): mkdir('C:\\xampp\\htdocs...', 509, true)
#2 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Cache\Engine\FileEngine.php(184): Cake\Cache\Engine\FileEngine->_setKey('myapp_cake_core...')
#3 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\debug_kit\src\Cache\Engine\DebugEngine.php(149): Cake\Cache\Engine\FileEngine->read('myapp_cake_core...')
#4 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\I18n\TranslatorRegistry.php(148): DebugKit\Cache\Engine\DebugEngine->read('translations.de...')
#5 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\I18n\I18n.php(204): Cake\I18n\TranslatorRegistry->get('debug_kit')
#6 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\I18n\functions.php(88): Cake\I18n\I18n::getTranslator('debug_kit')
#7 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\debug_kit\src\Panel\TimerPanel.php(35): __d('debug_kit', 'Event: View.bef...')
#8 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Event\EventManager.php(416): DebugKit\Panel\TimerPanel->DebugKit\Panel\{closure}(Object(Cake\Event\Event), 'C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Event\EventManager.php(393): Cake\Event\EventManager->_callListener(Object(Closure), Object(Cake\Event\Event))
#10 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(110): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#11 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\View\View.php(764): Cake\View\View->dispatchEvent('View.beforeRend...', Array)
#12 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(364): Cake\View\View->render('error500', 'error')
#13 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(343): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500')
#14 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(200): Cake\Error\ExceptionRenderer->_outputMessage('error')
#15 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(113): Cake\Error\ExceptionRenderer->render()
#16 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(97): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(ErrorException), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 C:\xampp\htdocs\vuokravalvonta\src\Middleware\ErrorHandlerMiddleware.php(74): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#18 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Http\Runner.php(65): App\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#21 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 C:\xampp\htdocs\vuokravalvonta\vendor\cakephp\cakephp\src\Http\Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#23 C:\xampp\htdocs\vuokravalvonta\webroot\index.php(37): Cake\Http\Server->run()
#24 {main}
```

### What you expected to happen
I guess, it should not trigger error ;)

**Comment by markstory** [comment]
Do you have the scream extension installed? The referenced line has error suppression enabled https://github.com/cakephp/cakephp/blob/9d6ceb6ad2511c26a695c8b7c6cc12ffa419d688/src/Cache/Engine/FileEngine.php#L384

**Comment by makallio85** [comment]
No, as far as I understand. Any idea how to check it? I have pretty much just default XAMPP installation.

**Comment by markstory** [comment]
Usually it would show up in `php -m`

**Comment by makallio85** [comment]
Seems that scream extension is not enabled, right?

```
$ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
imap
intl
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
pthreads
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
wddx
xdebug
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]
Xdebug
```

**Comment by makallio85** [comment]
I can confirm, that this same problem occurs on our private installation on GitLab CE 9.4.3 CI. We are using GitLab Multirunners (version 9.5.0) that are running on CentOS7 with docker containers.

.gitlab-ci.yml configuration:
```
services:
  - mariadb:10.1

variables:
  MYSQL_DATABASE: test
  MYSQL_ROOT_PASSWORD: password

before_script:
- set -xe
- apt-get update -yqq
- apt-get install git -yqq
- apt-get install libicu-dev -yqq
- apt-get install zlib1g-dev -yqq
- apt-get install libxml2-dev -yqq

- docker-php-ext-install intl
- docker-php-ext-install mbstring
- docker-php-ext-install pdo_mysql
- docker-php-ext-install zip

- curl -sS https://getcomposer.org/installer | php
- mv composer.phar /usr/local/bin/composer
- composer self-update
- composer install

test:7.0:
  image: php:7.0
  script:
  - vendor/bin/phpunit
  - ./sniff

test:7.1:
  image: php:7.1
  script:
  - vendor/bin/phpunit
  - ./sniff
```
