### ISSUE TITLE
void return type in AssociationTableMixinClassReflectionExtension

### ISSUE THREAD

**Issue by Zwaen91** [cakephp/cakephp#14467]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.11

### What you did
Run phpstan with custom config that enables Cake\PHPStan\AssociationTableMixinClassReflectionExtension as a service.

```
parameters:
    autoload_files:
        - tests/bootstrap.php
    earlyTerminatingMethodCalls:
        Cake\Shell\Shell:
            - abort

services:
    -
        class: Cake\PHPStan\AssociationTableMixinClassReflectionExtension
        tags:
            - phpstan.broker.methodsClassReflectionExtension
            - phpstan.broker.propertiesClassReflectionExtension
```

### What happened
Exception: Return value of Cake\PHPStan\AssociationTableMixinClassReflectionExtension::setBroker() must be an instance of Cake\PHPStan\void, none returned in [/builds/project-0/vendor/cakephp/cakephp/tests/PHPStan/AssociationTableMixinClassReflectionExtension.php, line 30]
Script vendor/bin/phpstan analyse -l 5 -c tests/phpstan.neon src/ handling the phpstan event returned with error code 1
