### ISSUE TITLE
Cakephp home page (http://cakephp.org/) responsive bug

### ISSUE THREAD

**Issue by aleixfabra** [cakephp/cakephp#6168]
There's a responsive bug with the main image (http://cakephp.org/). This will fix de mistake:

```css
.hero img {
  max-width: 100%;
  height: auto;
}
```

Maybe all web images should be:

```css
img {
    max-width: 100%;
    height: auto;
}
```

There's also another bug with the download button. This will fix it:
```css
@media (max-width: 768px) {
    .hero .polygon-button-shadow {
        right: 0;
        bottom: -55px;
    }
    .hero .polygon-button {
        top: -40px
        right: 0;
    }
}
